server:
  port: 9991


spring:
  application:
    name: cloudrs-register-node1

eureka:
  instance:
    hostname: register-node1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #serviceUrl:
      #defaultZone: http://register-node2.cloudrs:9992/eureka/,http://register-node3.cloudrs:9993/eureka/
  server:
    renewalPercentThreshold: 0.49
