server:
  port: 8762


spring:
  datasource:
    url: jdbc:mysql://mysql-master:3306/uc?useUnicode=true&characterEncoding=utf-8&&useSSL=false&&serverTimezone=Asia/Shanghai&&allowPublicKeyRetrieval=true
    username: dev
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: INFO
    org.springframework.security: info