server:
  port: 8765


spring:
  datasource:
    url: jdbc:mysql://mysql-master:3306/payment?useUnicode=true&characterEncoding=utf-8&&useSSL=false&&serverTimezone=Asia/Shanghai&&allowPublicKeyRetrieval=true
    username: dev
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

