eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9991/eureka/
server:
  port: 8762

spring:
  application:
    name: server1
  sleuth:
      web:
        client:
          enabled: true
      sampler:
          probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  cloud:
      config:
        discovery:
          enabled: true
          serviceId: cloudrs-config
        fail-fast: true
        label: master
        profile: dev
        retry:
          initial-interval: 1000
          max-attempts: 6
          max-interval: 2000
          multiplier: 1.1
  rabbitmq:
     host: 14.116.177.218
     password: guest
     port: 5672
     username: guest
#  zipkin:
#    base-url: http://localhost:9412/ # 指定了 Zipkin 服务器的地址