server:
  port: 8600

spring:
  application:
    name: cloudrs-turbine
  rabbitmq:
    addresses: rabbit1:5672,rabbit2:5672,rabbit3:5672
    username: cheng
    password: 123456

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    health-check-url-path: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://cloudrs-register:9991/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"


turbine:
  app-config: cloudrs-payment,cloudrs-auth,cloudrs-gateway,cloudrs-uc
  aggregator:
    # turbine聚集数据的粒度
    clusterConfig: default
  clusterNameExpression: new String("default")
  combine-host-port: true
